# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - UndergroundLondonTravel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: docker/login-action@v2
        with:
          registry: mcr.microsoft.com/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7FD84A2FE3DA458BAB77FCD55C0CE6D3 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_29BBB879C802495DA2E436A19F8E5B5A }}
          

      - name: Build and Push container to registry
        run: |
          docker build -t mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }} .
          docker push mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E36857FC84BE4E16B067296EE187372A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A80193C8A01245C89997705BBF5DF92F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_94EE2AD9BD704075A2CDD202FD760F1A }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'UndergroundLondonTravel'
          slot-name: 'Production'
          images: 'mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}'
          
